apiVersion: v1
kind: Service
metadata:
  name: rhythmforge
  namespace: rhythmforge
spec:
  selector:
    app: rhythmforge
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
